version: "3.8" 
services: 
 haproxy: 
 image: haproxy:2.7 
 container_name: haproxy 
 ports: 
 - "80:80" 
 - "443:443" 
 volumes: 
 - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro 
 - ./certs:/etc/haproxy/certs:ro 
 depends_on: 
 - app1 
 - app2 
 app1: 
 build: ./app 
 container_name: app1 
 ports: 
 - "8081:8080" 
 app2: 
 build: ./app 
 container_name: app2 
 ports: 
 - "8082:8080" 
networks: 
 default: 
 driver: bridge
